spring.application.name=SehatVaultBackend

# Supabase PostgreSQL Configuration (Development)
spring.datasource.url=jdbc:postgresql://db.bvjphekkgeoclhyguikl.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=m3Slh7oAt1BiFQIf
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

server.port=8080

# H2 console (optional)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JWT
jwt.secret=SehatVault_Local_Secret_Key_Change_For_Production_At_Least_256_Bits_Long_2026
jwt.expiration=86400000

# Actuator
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
