/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as assetTokenSol from './AssetToken.sol/index.js';
export * as counterSol from './Counter.sol/index.js';
export * as healthTokenSol from './HealthToken.sol/index.js';
export * as hospitalFinancialsSol from './HospitalFinancials.sol/index.js';