/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface HospitalFinancialsInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BANK_ROLE"
      | "DEFAULT_ADMIN_ROLE"
      | "FINANCE_ROLE"
      | "assetToken"
      | "depositAmountAT"
      | "depositOwner"
      | "depositProcessed"
      | "distributeProfit"
      | "getRoleAdmin"
      | "grantRole"
      | "hasRole"
      | "healthToken"
      | "hospitalWallet"
      | "mintAssetToken"
      | "nextTradeId"
      | "recordTrade"
      | "redeemHealthToken"
      | "renounceRole"
      | "revokeRole"
      | "supportsInterface"
      | "trades"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AssetTokenMinted"
      | "HealthTokenRedeemed"
      | "ProfitDistributed"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "TradeRecorded"
  ): EventFragment;

  encodeFunctionData(functionFragment: "BANK_ROLE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "FINANCE_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "assetToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "depositAmountAT",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "depositOwner",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "depositProcessed",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "distributeProfit",
    values: [BigNumberish, AddressLike[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "healthToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hospitalWallet",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "mintAssetToken",
    values: [AddressLike, BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "nextTradeId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "recordTrade",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "redeemHealthToken",
    values: [AddressLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "trades",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "BANK_ROLE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "FINANCE_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "assetToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositAmountAT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositProcessed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "distributeProfit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "healthToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hospitalWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintAssetToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextTradeId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordTrade",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "redeemHealthToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "trades", data: BytesLike): Result;
}

export namespace AssetTokenMintedEvent {
  export type InputTuple = [
    patient: AddressLike,
    depositId: BigNumberish,
    amountAT: BigNumberish,
    timestamp: BigNumberish,
    metadata: string
  ];
  export type OutputTuple = [
    patient: string,
    depositId: bigint,
    amountAT: bigint,
    timestamp: bigint,
    metadata: string
  ];
  export interface OutputObject {
    patient: string;
    depositId: bigint;
    amountAT: bigint;
    timestamp: bigint;
    metadata: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HealthTokenRedeemedEvent {
  export type InputTuple = [
    patient: AddressLike,
    amountHT: BigNumberish,
    serviceType: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    patient: string,
    amountHT: bigint,
    serviceType: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    patient: string;
    amountHT: bigint;
    serviceType: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProfitDistributedEvent {
  export type InputTuple = [
    tradeId: BigNumberish,
    totalProfit: BigNumberish,
    distributedHT: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    tradeId: bigint,
    totalProfit: bigint,
    distributedHT: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    tradeId: bigint;
    totalProfit: bigint;
    distributedHT: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TradeRecordedEvent {
  export type InputTuple = [
    tradeId: BigNumberish,
    investedAT: BigNumberish,
    profitEarned: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    tradeId: bigint,
    investedAT: bigint,
    profitEarned: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    tradeId: bigint;
    investedAT: bigint;
    profitEarned: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface HospitalFinancials extends BaseContract {
  connect(runner?: ContractRunner | null): HospitalFinancials;
  waitForDeployment(): Promise<this>;

  interface: HospitalFinancialsInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BANK_ROLE: TypedContractMethod<[], [string], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  FINANCE_ROLE: TypedContractMethod<[], [string], "view">;

  assetToken: TypedContractMethod<[], [string], "view">;

  depositAmountAT: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  depositOwner: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  depositProcessed: TypedContractMethod<
    [arg0: BigNumberish],
    [boolean],
    "view"
  >;

  distributeProfit: TypedContractMethod<
    [
      tradeId: BigNumberish,
      recipients: AddressLike[],
      amountsHT: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  healthToken: TypedContractMethod<[], [string], "view">;

  hospitalWallet: TypedContractMethod<[], [string], "view">;

  mintAssetToken: TypedContractMethod<
    [
      patient: AddressLike,
      depositId: BigNumberish,
      amountAT: BigNumberish,
      metadata: string
    ],
    [void],
    "nonpayable"
  >;

  nextTradeId: TypedContractMethod<[], [bigint], "view">;

  recordTrade: TypedContractMethod<
    [investedAT: BigNumberish, profit: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  redeemHealthToken: TypedContractMethod<
    [patient: AddressLike, amountHT: BigNumberish, serviceType: string],
    [void],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  trades: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        investedAT: bigint;
        profitEarned: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BANK_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "FINANCE_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "assetToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "depositAmountAT"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "depositOwner"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "depositProcessed"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "distributeProfit"
  ): TypedContractMethod<
    [
      tradeId: BigNumberish,
      recipients: AddressLike[],
      amountsHT: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "healthToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "hospitalWallet"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "mintAssetToken"
  ): TypedContractMethod<
    [
      patient: AddressLike,
      depositId: BigNumberish,
      amountAT: BigNumberish,
      metadata: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "nextTradeId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "recordTrade"
  ): TypedContractMethod<
    [investedAT: BigNumberish, profit: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "redeemHealthToken"
  ): TypedContractMethod<
    [patient: AddressLike, amountHT: BigNumberish, serviceType: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "trades"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        investedAT: bigint;
        profitEarned: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  getEvent(
    key: "AssetTokenMinted"
  ): TypedContractEvent<
    AssetTokenMintedEvent.InputTuple,
    AssetTokenMintedEvent.OutputTuple,
    AssetTokenMintedEvent.OutputObject
  >;
  getEvent(
    key: "HealthTokenRedeemed"
  ): TypedContractEvent<
    HealthTokenRedeemedEvent.InputTuple,
    HealthTokenRedeemedEvent.OutputTuple,
    HealthTokenRedeemedEvent.OutputObject
  >;
  getEvent(
    key: "ProfitDistributed"
  ): TypedContractEvent<
    ProfitDistributedEvent.InputTuple,
    ProfitDistributedEvent.OutputTuple,
    ProfitDistributedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "TradeRecorded"
  ): TypedContractEvent<
    TradeRecordedEvent.InputTuple,
    TradeRecordedEvent.OutputTuple,
    TradeRecordedEvent.OutputObject
  >;

  filters: {
    "AssetTokenMinted(address,uint256,uint256,uint256,string)": TypedContractEvent<
      AssetTokenMintedEvent.InputTuple,
      AssetTokenMintedEvent.OutputTuple,
      AssetTokenMintedEvent.OutputObject
    >;
    AssetTokenMinted: TypedContractEvent<
      AssetTokenMintedEvent.InputTuple,
      AssetTokenMintedEvent.OutputTuple,
      AssetTokenMintedEvent.OutputObject
    >;

    "HealthTokenRedeemed(address,uint256,string,uint256)": TypedContractEvent<
      HealthTokenRedeemedEvent.InputTuple,
      HealthTokenRedeemedEvent.OutputTuple,
      HealthTokenRedeemedEvent.OutputObject
    >;
    HealthTokenRedeemed: TypedContractEvent<
      HealthTokenRedeemedEvent.InputTuple,
      HealthTokenRedeemedEvent.OutputTuple,
      HealthTokenRedeemedEvent.OutputObject
    >;

    "ProfitDistributed(uint256,uint256,uint256,uint256)": TypedContractEvent<
      ProfitDistributedEvent.InputTuple,
      ProfitDistributedEvent.OutputTuple,
      ProfitDistributedEvent.OutputObject
    >;
    ProfitDistributed: TypedContractEvent<
      ProfitDistributedEvent.InputTuple,
      ProfitDistributedEvent.OutputTuple,
      ProfitDistributedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "TradeRecorded(uint256,uint256,uint256,uint256)": TypedContractEvent<
      TradeRecordedEvent.InputTuple,
      TradeRecordedEvent.OutputTuple,
      TradeRecordedEvent.OutputObject
    >;
    TradeRecorded: TypedContractEvent<
      TradeRecordedEvent.InputTuple,
      TradeRecordedEvent.OutputTuple,
      TradeRecordedEvent.OutputObject
    >;
  };
}
