package com.SehatVault.SehatVaultBackend.marketplace.scheduler;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.context.event.ApplicationReadyEvent;
import org.springframework.context.event.EventListener;
import org.springframework.core.annotation.Order;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

import java.util.List;

/**
 * One-time DB schema fix: trade_at_settlements.trade_id was originally created with a
 * UNIQUE constraint, which limited the table to one settlement row per trade. That
 * silently broke multi-participant trade close — the second participation's INSERT
 * would hit the unique violation, the settlement record wouldn't be written, and the
 * UI's "PKR Before" column would fall back to the post-loss value (showing P/L = 0).
 *
 * The entity annotation has been corrected (unique now lives on participation_id), but
 * Hibernate's ddl-auto=update never drops constraints that were removed from
 * annotations. So we drop it here on startup. Idempotent — does nothing if already gone.
 *
 * Runs BEFORE StuckTradeSettler (Order 0) so any stuck-trade replay can use the fixed schema.
 */
@Slf4j
@Component
@Order(0)
@RequiredArgsConstructor
public class SettlementSchemaFixer {

    private final JdbcTemplate jdbcTemplate;

    @EventListener(ApplicationReadyEvent.class)
    public void dropLegacyTradeIdUnique() {
        try {
            // Find any single-column UNIQUE constraint on trade_at_settlements.trade_id.
            // Constraint names are auto-generated by Postgres so we can't hard-code them.
            List<String> names = jdbcTemplate.queryForList(
                    "SELECT con.conname "
                    + "FROM pg_constraint con "
                    + "JOIN pg_class rel ON rel.oid = con.conrelid "
                    + "JOIN pg_attribute att ON att.attrelid = con.conrelid AND att.attnum = ANY(con.conkey) "
                    + "WHERE rel.relname = 'trade_at_settlements' "
                    + "  AND con.contype = 'u' "
                    + "  AND att.attname = 'trade_id' "
                    + "  AND array_length(con.conkey, 1) = 1",
                    String.class);

            for (String name : names) {
                jdbcTemplate.execute("ALTER TABLE trade_at_settlements DROP CONSTRAINT \"" + name + "\"");
                log.info("Dropped legacy unique constraint {} on trade_at_settlements.trade_id "
                        + "(was blocking multi-participant trade settlements)", name);
            }
        } catch (Exception ex) {
            log.warn("Could not drop legacy unique constraint on trade_at_settlements.trade_id: {}",
                    ex.getMessage());
        }
    }
}
