// Short overview: Statements list with download and modal view.
// - Displays recent statements and provides a modal to view all statements.
// - Relation: used in Activity sidebar to centralize statement UI.
import React from 'react'
import { Button } from '@/components/ui/button'
import { Modal, ModalTrigger, ModalContent, ModalHeader, ModalTitle, ModalFooter, ModalClose } from '@/components/ui/Modal'
import { StatementItem } from '@/types/activity'
import { Download, FileText, Calendar } from 'lucide-react'
import { getTransactions } from './activityData'

type Props = { statements: StatementItem[] }

const generateStatementPDF = (statement: StatementItem) => {
  // Get all transactions for this month
  const allTransactions = getTransactions()
  const monthTransactions = allTransactions.filter(tx => {
    const txDate = new Date(tx.created_at)
    return txDate.getMonth() === new Date(`${statement.month} 1, ${statement.year}`).getMonth() &&
           txDate.getFullYear() === statement.year
  })

  // Create statement content
  const statementContent = `
TRANSACTION STATEMENT
${statement.month} ${statement.year}

Patient Account Summary
Generated: ${new Date(statement.generatedDate).toLocaleDateString()}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

MONTHLY SUMMARY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Total Transactions: ${statement.transactions}
Total AT Transactions: ${statement.totalAT >= 0 ? '+' : ''}${statement.totalAT} AT
Total HT Transactions: ${statement.totalHT >= 0 ? '+' : ''}${statement.totalHT} HT

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

TRANSACTION DETAILS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

${monthTransactions.length > 0 ? monthTransactions.map((tx, idx) => `
${idx + 1}. ${tx.token_type} Transaction
   Date: ${new Date(tx.created_at).toLocaleString()}
   Amount: ${tx.amount >= 0 ? '+' : ''}${tx.amount} ${tx.token_type}
   Status: ${tx.status.toUpperCase()}
   Tx Hash: ${tx.transaction_hash || 'N/A'}
   ${tx.token_type === 'AT' ? `From: ${tx.from_address || 'N/A'}
   To: ${tx.to_address || 'N/A'}
   Token ID: ${tx.token_id || 'N/A'}
   Gas Used: ${tx.gas_used?.toLocaleString() || 'N/A'}` : `Patient ID: ${tx.patient_id || 'N/A'}
   Type: ${tx.type || 'N/A'}
   Source: ${tx.source || 'N/A'}
   Block: ${tx.block_number?.toLocaleString() || 'N/A'}`}
`).join('\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n') : 'No transactions found for this period.'}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

This is an automated statement generated by the SehatVault Platform.
For inquiries, please contact support@sehatvault.com

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
`

  // Create a blob and download
  const blob = new Blob([statementContent], { type: 'text/plain' })
  const url = window.URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `statement-${statement.month}-${statement.year}.txt`
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  window.URL.revokeObjectURL(url)
}

export default function StatementsList({ statements }: Props) {
  return (
    <div>
      <div className="space-y-3">
        {statements.slice(0, 3).map((s) => (
          <div key={s.id} className="p-4 border rounded-lg hover:bg-muted/50 transition-colors">
            <div className="flex items-center justify-between">
              <div className="flex items-start gap-3 flex-1">
                <div className="p-2 bg-primary/10 rounded-lg">
                  <FileText className="w-5 h-5 text-primary" />
                </div>
                <div className="flex-1">
                  <div className="font-semibold">{s.month} {s.year}</div>
                  <div className="flex items-center gap-4 mt-1 text-sm text-muted-foreground">
                    <span className="flex items-center gap-1">
                      <Calendar className="w-3 h-3" />
                      Generated: {new Date(s.generatedDate).toLocaleDateString()}
                    </span>
                  </div>
                  <div className="flex items-center gap-4 mt-2 text-xs">
                    <span className="px-2 py-0.5 bg-blue-100 text-blue-700 rounded">
                      {s.transactions} Transactions
                    </span>
                    <span className="text-muted-foreground">
                      AT: {s.totalAT >= 0 ? '+' : ''}{s.totalAT}
                    </span>
                    <span className="text-muted-foreground">
                      HT: {s.totalHT >= 0 ? '+' : ''}{s.totalHT}
                    </span>
                  </div>
                </div>
              </div>
              <Button 
                variant="outline" 
                size="sm"
                onClick={() => generateStatementPDF(s)}
                className="flex items-center gap-2"
              >
                <Download className="w-4 h-4" />
                Download
              </Button>
            </div>
          </div>
        ))}
      </div>

      <div className="pt-4 border-t mt-4">
        <div className="w-full flex items-center justify-end">
          <Modal>
            <ModalTrigger asChild>
              <Button variant="link">View all statements</Button>
            </ModalTrigger>
            <ModalContent className="max-w-3xl">
              <ModalHeader>
                <ModalTitle>All Monthly Statements</ModalTitle>
              </ModalHeader>
              <div className="mt-2 max-h-[60vh] overflow-auto space-y-3 p-4">
                {statements.map((s) => (
                  <div key={s.id} className="p-4 border rounded-lg hover:bg-muted/50 transition-colors">
                    <div className="flex items-center justify-between">
                      <div className="flex items-start gap-3 flex-1">
                        <div className="p-2 bg-primary/10 rounded-lg">
                          <FileText className="w-5 h-5 text-primary" />
                        </div>
                        <div className="flex-1">
                          <div className="font-semibold">{s.month} {s.year}</div>
                          <div className="flex items-center gap-4 mt-1 text-sm text-muted-foreground">
                            <span className="flex items-center gap-1">
                              <Calendar className="w-3 h-3" />
                              {new Date(s.generatedDate).toLocaleDateString()}
                            </span>
                          </div>
                          <div className="flex items-center gap-4 mt-2 text-xs">
                            <span className="px-2 py-0.5 bg-blue-100 text-blue-700 rounded">
                              {s.transactions} Transactions
                            </span>
                            <span className="text-muted-foreground">
                              AT: {s.totalAT >= 0 ? '+' : ''}{s.totalAT}
                            </span>
                            <span className="text-muted-foreground">
                              HT: {s.totalHT >= 0 ? '+' : ''}{s.totalHT}
                            </span>
                          </div>
                        </div>
                      </div>
                      <Button 
                        variant="outline" 
                        size="sm"
                        onClick={() => generateStatementPDF(s)}
                        className="flex items-center gap-2"
                      >
                        <Download className="w-4 h-4" />
                        Download
                      </Button>
                    </div>
                  </div>
                ))}
              </div>
              <ModalFooter>
                <ModalClose asChild>
                  <Button variant="outline">Close</Button>
                </ModalClose>
              </ModalFooter>
            </ModalContent>
          </Modal>
        </div>
      </div>
    </div>
  )
}
